# Generated by Django 5.2.4 on 2025-07-27 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilioImplAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'phone',
            },
        ),
        migrations.AddField(
            model_name='login',
            name='salt',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='twilioImplAPI.phone'),
        ),
    ]
